name: Debian Repository Bot
on:
  workflow_run:
    workflows: [Debian Build Bot]
    types: [completed]

jobs:
  generate:
    name: Generate Debian repository files
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: ${{ github.event.workflow_run.head_branch }}
        run: echo "Generating with ${{ github.event.workflow_run.head_branch }}"
      - uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
          fetch-depth: '0'
      - working-directory: ${{ github.event.repository.name }}
        run: |
          PREVIOUS_TAG=`git describe --abbrev=0 --tags ${{ github.event.workflow_run.head_branch }}^`
          echo "PREVIOUS_TAG=${PREVIOUS_TAG}" >> $GITHUB_ENV
      - uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.event.workflow_run.head_branch }}
          out-file-path: download/${{ github.event.workflow_run.head_branch }}
          fileName: '*'
      - uses: robinraju/release-downloader@v1
        with:
          tag: ${{ env.PREVIOUS_TAG }}
          out-file-path: download/${{ github.event.workflow_run.head_branch }}
          fileName: 'Packages'
      - uses: robinraju/release-downloader@v1
        with:
          tag: ${{ env.PREVIOUS_TAG }}
          out-file-path: download/${{ github.event.workflow_run.head_branch }}
          fileName: 'Sources'
      - working-directory: download/${{ github.event.workflow_run.head_branch }}
        run: |
          dpkg-scanpackages -m ../../download/${{ github.event.workflow_run.head_branch }} >> Packages
          dpkg-scansources ../../download/${{ github.event.workflow_run.head_branch }} >> Sources
          apt-ftparchive release . > Release
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: |
            download/${{ github.event.workflow_run.head_branch }}/Packages
            download/${{ github.event.workflow_run.head_branch }}/Sources
            download/${{ github.event.workflow_run.head_branch }}/Release
